---
- name: Gather facts and display them
  hosts: ubuntu
  gather_facts: true
  tasks:
    - name: Display gathered facts
      ansible.builtin.debug:
        var: ansible_facts

    - name: Display specific fact (e.g., OS family)
      ansible.builtin.debug:
        msg: "The kernel is {{ ansible_facts['kernel'] }} and the distribution is {{ ansible_facts['distribution'] }}."
