---
- name: Quick web server install and config
  hosts: ubuntu
  gather_facts: false
  become: true
  tasks:
    - name: Install Apache web server
      ansible.builtin.package:
        name: apache2
        state: present

    - name: Start Apache service
      ansible.builtin.service:
        name: apache2
        state: started
        enabled: true

    - name: Write a simple HTML file
      ansible.builtin.lineinfile:
        path: /var/www/html/index.html
        line: "<h1>Hello, World!</h1>"
        create: true